#!/bin/env bash
alias la="ls -a"
alias sudo="sudo"
alias dotfiles="cd ~/.dotfiles"
alias symlinks="$DOTFILES_PATH/symlinks/links.sh"

# updates
alias zimup="zimfw update && zimfw upgrade"
alias up="sudo apt update"
alias ug="sudo apt dist-upgrade -y"

alias gtj="go_to_job"
alias gtd="go_to_dev"
alias opj="open_job"
alias opd="open_dev"

# gits
alias c="clear"
alias gs="git status"
alias gl="git log --graph --abbrev-commit "

alias gc="git commit -m $*"
alias gce="git commit --allow-empty -m $*"
alias gmdc="npx miduco"
alias gca=" git commit --amend --no-edit"

alias grA="git restore ."  

alias grb="git branch | fzf | xargs -I_ git rebase _"
alias grbc="git rebase --continue"
alias grba="git rebase --abort"
alias grbs="git rebase --skip"

alias gm="git branch | grep -v '\*' | fzf | xargs -I_ git merge _"
alias gmc="git merge --continue"
alias gma="git merge --abort"
alias gms="git merge --skip"

alias gsts="git stash save"
alias gsta="git stash apply"
alias gstc="git stash clear"

alias gbs="git bisect start"
alias gbg="git bisect good"
alias gbb="git bisect bad"
alias gbr="git bisect reset"

alias gswc="git switch -c $1"
alias gb="git branch"

alias gr="git reset --soft HEAD~1"

alias gf="git fetch --all -p"

alias gbd="git branch | grep -v '\*' | fzf | xargs -I_ git branch -D _"

# clone repos
alias ghcl="clone_git_repo"
alias glcl="clone_gitlab_repo"

# install - uninstall dependencies
alias installsub="find . -name 'package.json' -execdir npm install \;"
alias uninstallsub="find . -name 'node_modules' -type d -prune -exec rm -rf {} +"