#!/bin/env bash
  # VS Code
export_exte(){
  echo "Exportando extenciones de vsCode..."
  if [[ -a "$DOTFILES_PATH/os/vscode-extensions" ]]; then
    rm "$DOTFILES_PATH/os/vscode-extensions"
  fi
  code --list-extensions | xargs -L 1 echo code --install-extension > "$DOTFILES_PATH/os/vscode-extensions"
  echo "Extenciones exportadas!!"

}

import_exte() {
  "$DOTFILES_PATH/os/vscode-extensions"
}