#!/bin/env bash
# function lazy_nvm {
#   unset -f nvm
#   unset -f npm
#   unset -f node
#   unset -f npx
#   unset -f yarn

#   if [ -d "${HOME}/.nvm" ]; then
#     export NVM_DIR="$HOME/.nvm"
#     [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # linux
#   fi
# }

# # aliases
# function nvm { lazy_nvm; nvm "$@"; }
# function npm { lazy_nvm; npm "$@"; }
# function node { lazy_nvm; node "$@"; }
# function npx { lazy_nvm; npx "$@"; }
# function yarn { lazy_nvm; yarn "$@"; }


# function deno_lazy {
#   unset -f deno

#   if [ -d "${HOME}/.deno" ]; then
#     export DENO_INSTALL="$HOME/.deno"
#     export PATH="$DENO_INSTALL/bin:$PATH"
#   fi
# }

# function deno { deno_lazy; deno "$@"; }
